server:
  port: 8084
spring:
  application:
    name: question-service
  datasource:
    url: ${DS_URL:jdbc:postgresql://localhost:5432/exam2}
    username: ${DS_USERNAME:postgres}
    password: ${DS_PASSWORD:123456}
services:
  subject:
    url: ${SUBJECT_SERVICE_URL:http://localhost:8083}
mybatis:
  mapper-locations: classpath:/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
jwt:
  secret: ${JWT_SECRET:exam-jwt-secret-key-must-be-at-least-32-chars}
