apiVersion: v1
kind: ConfigMap
metadata:
  name: exam-config
  namespace: exam-system
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: exam2
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
